### ISSUE TITLE
Add support for source maps

### ISSUE THREAD

**Issue by searls** [testdouble/function-names-at-line#1]
I know almost nothing about working with sourcemaps programmatically.

Tagging in @garybernhardt to consider how we might do this

**Comment by garybernhardt** [comment]
For tracebacks, it's easy:

1. Install the source-map-support module.
2. Run the setup code in your test_helper file:

```javascript
require('source-map-support').install({
  handleUncaughtExceptions: false
});
```

3. Tracebacks now respect sourcemaps and refer to your original source files! Note the .ts file in the last line here, even though I ran teenytest on the `build` directory that was generated by `tsc`.

```
#     AssertionError [ERR_ASSERTION]: Expected values to be strictly deep-equal:
#
#     1 !== 2
#
#         at Decorator._callFunc (/Users/grb/proj/ltr/node_modules/empower-core/lib/decorator.js:110:20)
#         at Decorator.concreteAssert (/Users/grb/proj/ltr/node_modules/empower-core/lib/decorator.js:103:17)
#         at Function.decoratedAssert (/Users/grb/proj/ltr/node_modules/empower-core/lib/decorate.js:51:30)
#         at Object.module.exports.selects nodes (/Users/grb/proj/ltr/src/backend/graph.test.ts:188:3)
```

**Comment by garybernhardt** [comment]
(Sorry, the above is for teenytest; I forgot that this package is separate.)

**Comment by garybernhardt** [comment]
Hang on, I'm generating a patch to support source aps.

**Comment by garybernhardt** [comment]
That went extremely badly.

I'm leaning toward the opinion that this module shouldn't exist and teenytest should give up on running tests by line number. We can't know what ES version the user is running, so we can't know which version of Acorn is appropriate. Am I missing something?

**Comment by garybernhardt** [comment]
If there were a `test` function for defining tests, then I think that this would be extremely easy. Create a `new Error` and extract traceback info from it. Then:

* teenytest doesn't need this module any more
* everything is much simpler
* the test runner doesn't depend on a JS parser of unknown compatibility with the user's code
* and source map support comes for free via the source-map-support module.

**Comment by searls** [comment]
It seems that to solve the broader problem of "run the test at line 5", we're missing a step. Trying to think through the steps necessary here:

1. Suppose a user is writing TypeScript (or even a non-JS superset language like PureScript or Elm). They'll look at their uncompiled source file in their editor and say "yes run whatever test is at line 5". 
2. Given the raw source map, we could ask the [source-map](https://github.com/mozilla/source-map) package `consumer.generatedPositionFor({line: 5…})` and get back `{line: 7, column: 14}` 
3. Then, the behavior of this package might not need to change—we could pass the compiled JS source and line `6` to this function and get back the function names at that line

Step 3 is what this module already does and it wouldn't necessarily(?) change. All that's really new to us is step 2. I could imagine a module `generatedLine(srcLine, generatedPath)` that scans the file at `generatedPath` for a source map URL, loads it, and passes it to `source-map` to ask for the generated line for the given `srcLine`.

Seems like that kinda might work?

**Comment by garybernhardt** [comment]
Yes, that's what I was doing and I think it will work. It requires making the index function async, plus accepting a path rather than a source string, so it's a major version bump. But while I was doing that I realized that we don't even know if the code that the user is running is parseable by our version of Acorn, which is why I don't think that this module should be using a parser at all.

**Comment by searls** [comment]
> But while I was doing that I realized that we don't even know if the code that the user is running is parseable by our version of Acorn, which is why I don't think that this module should be using a parser at all.

Seems like a valid concern but because ES is generally pretty backwards-compatible and compile-to targets are generally pretty safely old, I wonder how much of a risk this really is? As an aside, since it'll be run in the same process as the test runner, could we use `process.version` (`'v10.15.1'`) to guesstimate what ES version they're assuming?
